sudo: false
language: node_js
node_js:
- '15'
env:
- TSI2_LING7='build'
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
before_deploy:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: c0J8L/ICr5wbeHNkLZccp0nsxw+L7crwWPPln6tAh/IFjw+fgMb2Z7nDuU1GbxVFt2584uXV2chheDKtA+7Ot2oHgI97SvdZx85sNCJkDJJs67TXqjiGkC7jFcEEh2YKMDNVMD8Kf5zhZnzNlTq0ZeeWAP1BbHokdrXGT2cYUgdLCq6F0trHD2FYBf8cHSiK82D4otl/5CmPiVwLPxh/+mDurtLT1zGtd+iI9RZzYTal4Ps+qxg7bWLVbyIKgNqIaKjxzfPqk4ZxnlWrUAXrzhU4A5fbW6MbYnPkxvqyfJtFmVqQmPAUyJH56FKyVYotbRimJz3upo+aVn0KBlZgkj9rU5CWwGRJUJZMGMeI/36c2Zp9hvCOdusdxAGtumWPbnjzaZS5ks0FOE16REEg4IJDCM/Si3dXIJzsfbNaDaYMpUc4saYoNCSvSH0TPCXOAxds5oHwtlaiPHreL/1YmL1oVnqlFOjr+umW7HQxbcowi7hhOt5rLq3xSPdy0o0+r50vlPLRGjTXDCElLEVLUrUhT/yNQ/ACU2WOg7hMEI8EQ82qFTmQiJgeWXjyJjA/bhs3yRP0HWz2yYFlEPmb5TsyrZhRzGpKTZrDer1fHjA7dAsLF8zXTQn1mUhBEYYdYJQMnGVLdME/2qcfE9iGhunQnmqBGtcPmWo/FH2n2kA=
  local_dir: build/
  name: iTaiGi Auto Deploy Bot
