sudo: false
language: node_js
node_js:
- '15'
env:
- TSI2_LING7='build'
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
before_deploy:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: R6BGRN01db2Sos0fysHUme06KBNPk2GQVhwHhTK8eIjD6VzBjo/tB1UbJgeFaO5PrZA3pZi71j0zoijh0cfI9HrZSsKQmgPoi1o4a1I864R/RGYxkELZK2R3YWIanKyxStl8pO8dH5ZNcohYkwVVgLGksFlmllX8ZdV2h9Jh0/IyOp6WZCRdU5sMmQU7f+2zjtkjAKmAUp0fLBHjrXxH3lflhGHVk7BDtynTtyDkD9SMqnD8OySVXb4LdlHSd1WYzp2cHVTECCe3PXn1WrqJSGw+ZO+rm2JlX1VnSaOuzgK9YIJuKxvGS4dvb1Vu3BIfmIm9DnfxAgwpHYqDvhEP/gZh16OeY9RHUhZfLrjPxrre9klmYZNtKxlap1NeII/SZtBc7Sp2e4qFLmqcM3nbfejcz7pYsF2ChPL7BT6ou7+IKOZ3ym30JPlrNmOOQcOlX8rYBe5qc9oPonq+Hvuq4Em4WaGYpDErKdPMdQxzH2jrXI3RGg8gwsWsT106yLy/0GBhLyQqLuOhQTm8U2i9okfTP4CZIhEaQZW5JW6BFFhzdAFEpO+0rQ3+x+wHstHJ7S/S/Atq2DmEB4PyChs+m56bYObGJYFCCA8l00qV1SDXm2LIXF73fzaPuUxquNuNobkRHoRA3suqtNNxMi9xL6ycTmt7iW7vpRaS+ou6jO4=
  local_dir: build/
  name: iTaiGi Auto Deploy Bot
  on:
    branch: master
