sudo: false
install:
- pip install tox
- sudo apt-get install libsndfile1
script:
- tox -e $TOX_ENV
jobs:
  include:
    - name: "checkmigrations"
      env: TOX_ENV=checkmigrations
    - name: "flake8"
      env: TOX_ENV=flake8
    - name: "npm build"
      language: node_js
      node_js:
        - '16'
      install:
        - npm install
      script:
        - npm run build
