version: '3.5'

services:
  gunicorn:
    build: ./
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: ${DEPLOY_HOST:-itaigi.tw}
      LETSENCRYPT_HOST: ${DEPLOY_HOST:-itaigi.tw}
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
      SECRET_KEY: ${SECRET_KEY}
    restart: always
  pgsql:
    image: postgres:13
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=300'
    shm_size: '256mb'
    restart: always
    environment:
      POSTGRES_PASSWORD: itaigi
    volumes:
      - pgsql_data:/var/lib/postgresql/data
  celery_beat:
    build: ./
    command: celery -A itaigi beat -l info
    environment:
      SECRET_KEY: ${SECRET_KEY}
    restart: always
  celery:
    build: ./
    command: celery -A itaigi worker -l info
    environment:
      SECRET_KEY: ${SECRET_KEY}
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    environment: 
      RABBITMQ_DEFAULT_USER: itaigi
      RABBITMQ_DEFAULT_PASS: itaigi
      RABBITMQ_DEFAULT_VHOST: itaigi
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: always

volumes:
  pgsql_data:
  rabbit_data:

networks:
  nginx-bridge:
    external: true
